### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@TomasVotruba What made the build fail?

**Comment by TomasVotruba** [comment]
You can see it here: https://travis-ci.com/rectorphp/compiler/builds/119060166

**Comment by TomasVotruba** [comment]
This package needs still 50 % of work to finished and I focus on main Rector development, so I don't follow it

**Pull request merged**
