### PR TITLE
Fix the Box configuration

### PR DESCRIPTION
**Pull request by theofidry**
This should fix the Box configuration. It looks like however there is more work to do regarding the PHP-Scoper configuration

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This is not needed. Actually, the build works and local `composer.json` is not used at all. This package compiles https://github.com/rectorphp/rector - it's `composer.json` is used. It has the bin - that's all right: https://github.com/rectorphp/rector/blob/master/composer.json#L117

**The problem is the initial `prefixed\getcwd()` function autoload**, as you can see in Travis: https://travis-ci.com/rectorphp/compiler/builds/99439934#L783

image

**Comment by TomasVotruba** [comment]
Do you have time now? What do you use for chat? I'd love to close this, since it's the biggest Rector blocker now

**Comment by theofidry** [comment]
I can probably take a look at it in more details tomorrow. Am I reading it correctly that the requirement checker is being run twice on the CI?

**Comment by TomasVotruba** [comment]
The failing autoload function is the only issue. Everything else is now irrelevant.

**Comment by theofidry** [comment]
Looks simple:

<details>
<summary>vendor/paragonie/sodium_compat/autoload.php</summary>

```php
<?php

namespace _HumbugBoxe57a18add80e;

if (!\is_callable('sodiumCompatAutoloader')) {
    /**
     * Sodium_Compat autoloader.
     *
     * @param string $class Class name to be autoloaded.
     *
     * @return bool         Stop autoloading?
     */
    function sodiumCompatAutoloader($class)
    {
        $namespace = 'ParagonIE_Sodium_';
        // Does the class use the namespace prefix?
        $len = \strlen($namespace);
        if (\strncmp($namespace, $class, $len) !== 0) {
            // no, move to the next registered autoloader
            return \false;
        }
        // Get the relative class name
        $relative_class = \substr($class, $len);
        // Replace the namespace prefix with the base directory, replace namespace
        // separators with directory separators in the relative class name, append
        // with .php
        $file = \dirname(__FILE__) . '/src/' . \str_replace('_', '/', $relative_class) . '.php';
        // if the file exists, require it
        if (\file_exists($file)) {
            require_once $file;
            return \true;
        }
        return \false;
    }
    // Now that we have an autoloader, let's register it!
    \spl_autoload_register('sodiumCompatAutoloader');
}
require_once \dirname(__FILE__) . '/src/SodiumException.php';
if (\PHP_VERSION_ID >= 50300) {
    // Namespaces didn't exist before 5.3.0, so don't even try to use this
    // unless PHP >= 5.3.0
    require_once \dirname(__FILE__) . '/lib/namespaced.php';
    require_once \dirname(__FILE__) . '/lib/sodium_compat.php';
}
if (\PHP_VERSION_ID < 70200 || !\extension_loaded('sodium')) {
    require_once \dirname(__FILE__) . '/lib/php72compat.php';
}

```

</details>

`!\is_callable('sodiumCompatAutoloader')` should be `!\is_callable('_HumbugBoxe57a18add80e\sodiumCompatAutoloader')`

and `\spl_autoload_register('sodiumCompatAutoloader');` should be `    \spl_autoload_register('_HumbugBoxe57a18add80e\sodiumCompatAutoloader');`.

I think you can fix it with a PHP-Scoper patcher for now, but it's definitely a bug on PHP-Scoper side. I guess I forgot about `is_callable()`

**Comment by TomasVotruba** [comment]
Not sure what you mean. Could you show me in PR so the build passes?

**Comment by TomasVotruba** [comment]
Not sure what you mean. Could you show me in PR to make the build pass?

**Comment by TomasVotruba** [comment]
Also, it's this still the Safe\getcwd issue:  https://github.com/humbug/box/issues/352

**Comment by theofidry** [comment]
I can't as I'm not on a computer with PHP installed right now. 

I'm referring to [those patchers](https://github.com/humbug/php-scoper#patchers) to manually alter the content of the scoped files to your liking. You see in the snippet above that you have:

```
namespace _HumbugBoxe57a18add80e;

function sodiumCompatAutoloader($class) {};
```

So obviously `!\is_callable('sodiumCompatAutoloader')` is wrong since it should be `!\is_callable('_HumbugBoxe57a18add80e\sodiumCompatAutoloader')`.

So you need to do a `preg_replace()` call to replace the occurrences of `'sodiumCompatAutoloader'` into `'_HumbugBoxe57a18add80e\sodiumCompatAutoloader'` in that file

**Comment by TomasVotruba** [comment]
I don't understand. There is not issue with sodium. The Safe is the issue.

**Comment by TomasVotruba** [comment]
Closing as unrelated to original issue.

**Pull request closed without merging**
